export const CHANGE_WELCOME = 'CHANGE_WELCOME';

export const SET_INITIALIZED = 'SET_INITIALIZED';

export const SET_DISPLAY_LINES = 'SET_DISPLAY_LINES';

export const SET_SPEECH_DATA = 'SET_SPEECH_DATA';

